# Generated by Django 4.2.16 on 2026-04-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buspass',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from'))), name='ck_buspass_valid_until_after_valid_from'),
        ),
        migrations.AddConstraint(
            model_name='passapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'route', 'duration_type'), name='uq_pending_application_student_route_duration'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('name', 'source', 'destination'), name='uq_route_name_source_destination'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('distance_km__gt', 0)), name='ck_route_distance_positive'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('duration_min__gt', 0)), name='ck_route_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('fare__gt', 0)), name='ck_route_fare_positive'),
        ),
    ]

