# Generated by Django 6.0.4 on 2026-04-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_buspass_ck_buspass_valid_until_after_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passscanlog',
            name='conductor',
        ),
    ]
