# Generated by Django 6.0.4 on 2026-04-14 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_route_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='color',
            field=models.CharField(default='#1A4A8A', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code like #1A4A8A.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
