# Generated by Django 4.2.16 on 2026-04-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='ck_bus_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='buslocation',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='ck_buslocation_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='buslocation',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='ck_buslocation_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='buslocation',
            constraint=models.CheckConstraint(check=models.Q(('speed_kmh__gte', 0)), name='ck_buslocation_speed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='busschedule',
            constraint=models.CheckConstraint(check=models.Q(('stop_order__gte', 0)), name='ck_busschedule_stop_order_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='busschedule',
            constraint=models.UniqueConstraint(fields=('bus', 'stop_order'), name='uq_busschedule_bus_stop_order'),
        ),
    ]

