# Generated by Django 6.0.3 on 2026-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_ck_payment_amount_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('PASS_PURCHASE', 'Pass Purchase'), ('PASS_RENEWAL', 'Pass Renewal'), ('WALLET_TOPUP', 'Wallet Topup'), ('TICKET', 'Ticket')], max_length=20),
        ),
    ]
